name: jensketch
favicon: null
layout_spectrum: 0.58893
typography_spectrum: 0.79866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c4477'
    - '#768695'
    - '#3b2d13'
    - '#c4c8d1'
    - '#fcf8f5'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
